
my_svm : main.cc svm.cpp Tmy_svm.cc Tbase_dataframe.cc Tdataframe.cc Twrite_file.cc Tread_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc
	       g++ -o my_svm -std=c++17 main.cc svm.cpp Tmy_svm.cc Tbase_dataframe.cc Tdataframe.cc Twrite_file.cc Tread_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc -lstdc++fs -g -I.
