#!/bin/bash

# ID_EXPERIMENT_DT=1682513467
# ID_DETAIL_EXPERIMENT_DT=1682514676

ID_DT_TRAIN=1
JNS_DT_TRAIN=1 
PARTITION_TRAIN='p1'

ID_DT_TEST=1
JNS_DT_TEST=1
PARTITION_TEST='p1'

DEPTH=9
SAMPLE=4
THRESHOLD=2
CREDAL=2

GAMMA_AWAL=0.0001
GAMMA_AKHIR=0.0005
GAMMA_STEP=0.0001

NU_AWAL=0.01
NU_AKHIR=0.05
NU_STEP=0.01


# ./my_svmdb $ID_EXPERIMENT_DT $ID_DETAIL_EXPERIMENT_DT $GAMMA_AWAL $GAMMA_AKHIR $GAMMA_STEP $NU_AWAL $NU_AKHIR $NU_STEP
# wait

./my_svmdb $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST $DEPTH $SAMPLE $THRESHOLD $CREDAL $GAMMA_AWAL $GAMMA_AKHIR $GAMMA_STEP $NU_AWAL $NU_AKHIR $NU_STEP
wait



