#!/bin/bash

DEPTH_AWAL=6
DEPTH_AKHIR=30
DEPTH_STEP=1

MIN_SAMP_AWAL=2
MIN_SAMP_AKHIR=2
MIN_SAMP_STEP=2

CREDAL_S_AWAL=0.5
CREDAL_S_AKHIR=0.5
CREDAL_S_STEP=0.5

THRESHOLD_AWAL=2
THRESHOLD_AKHIR=2
THRESHOLD_STEP=2


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=21
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=21
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=21
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=21
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=21
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait



START="$(date +"%r")"
echo "START : $START"

ID_DT_TRAIN=22
JNS_DT_TRAIN=1 
PARTITION_TRAIN='p2'

ID_DT_TEST=22
JNS_DT_TEST=1
PARTITION_TEST='p2'

./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait

START="$(date +"%r")"
echo "START : $START"

ID_DT_TEST=22
JNS_DT_TEST=2
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait

START="$(date +"%r")"
echo "START : $START"

ID_DT_TEST=22
JNS_DT_TEST=3
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait

START="$(date +"%r")"
echo "START : $START"

ID_DT_TEST=22
JNS_DT_TEST=4
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=23
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=23
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=23
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=23
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=23
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=24
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=24
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=24
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=24
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=24
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=25
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=25
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=25
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=25
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=25
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=26
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=26
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=26
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=26
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=26
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=27
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=27
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=27
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=27
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=27
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=28
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=28
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=28
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=28
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=28
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=29
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=29
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=29
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=29
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=29
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=210
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p2'

# ID_DT_TEST=210
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=210
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=210
# JNS_DT_TEST=3
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=210
# JNS_DT_TEST=4
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait





ID_DT_TEST=211
JNS_DT_TEST=1
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
# wait

ID_DT_TEST=211
JNS_DT_TEST=2
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
# wait




