#!/bin/bash

DEPTH_AWAL=6
DEPTH_AKHIR=30
DEPTH_STEP=1

MIN_SAMP_AWAL=200
MIN_SAMP_AKHIR=400
MIN_SAMP_STEP=200

CREDAL_S_AWAL=0.0
CREDAL_S_AKHIR=2.0
CREDAL_S_STEP=0.5

THRESHOLD_AWAL=0.1
THRESHOLD_AKHIR=0.3
THRESHOLD_STEP=0.2


START="$(date +"%r")"
echo "START : $START"

ID_DT_TRAIN=1
JNS_DT_TRAIN=1 
PARTITION_TRAIN='p1'

ID_DT_TEST=1
JNS_DT_TEST=1
PARTITION_TEST='p1'

./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=1
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=1
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

START="$(date +"%r")"
echo "START : $START"

ID_DT_TEST=1
JNS_DT_TEST=4
PARTITION_TEST='p1'

./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait


START="$(date +"%r")"
echo "START : $START"

ID_DT_TEST=21
JNS_DT_TEST=1
PARTITION_TEST='p2'

./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

END="$(date +"%r")"
echo "START : $START END : $END"
wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=211
# JNS_DT_TEST=2
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=2
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=2
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=2
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=2
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=2
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=21
# JNS_DT_TEST=1
# PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=3
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=3
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=3
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=3
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=3
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=4
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=4
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=4
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=4
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=4
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=5
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=5
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=5
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=5
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=5
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=6
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=6
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=6
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=6
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=6
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait



# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=7
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=7
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=7
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=7
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=7
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=8
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=8
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=8
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=8
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=8
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=9
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=9
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=9
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=9
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=9
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TRAIN=10
# JNS_DT_TRAIN=1 
# PARTITION_TRAIN='p1'

# ID_DT_TEST=10
# JNS_DT_TEST=1
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=10
# JNS_DT_TEST=2
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait


# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=10
# JNS_DT_TEST=3
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait

# START="$(date +"%r")"
# echo "START : $START"

# ID_DT_TEST=10
# JNS_DT_TEST=4
# PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST

# END="$(date +"%r")"
# echo "START : $START END : $END"
# wait























ID_DT_TEST=11
JNS_DT_TEST=1
PARTITION_TEST='p1'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
# wait

ID_DT_TEST=211
JNS_DT_TEST=1
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
# wait

ID_DT_TEST=211
JNS_DT_TEST=2
PARTITION_TEST='p2'

# ./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
# wait





