#!/bin/bash

PATH_MODEL='Dataset/NSL/tree_dataset/tmp/coba' 

ID_DT_TRAIN=2
JNS_DT_TRAIN=1 
PARTITION_TRAIN='p21'

ID_DT_TEST=2
JNS_DT_TEST=1
PARTITION_TEST='p21'


DEPTH_AWAL=10
DEPTH_AKHIR=30
DEPTH_STEP=1

MIN_SAMP_AWAL=1000
MIN_SAMP_AKHIR=1000
MIN_SAMP_STEP=100

CREDAL_S_AWAL=0.0
CREDAL_S_AKHIR=2.0
CREDAL_S_STEP=0.5

THRESHOLD_AWAL=500
THRESHOLD_AKHIR=500
THRESHOLD_STEP=100

# mkdir ~/$PATH_MODEL

START="$(date +"%r")"
echo "START : $START"

./my_dtdb $DEPTH_AWAL $DEPTH_AKHIR $DEPTH_STEP $MIN_SAMP_AWAL $MIN_SAMP_AKHIR $MIN_SAMP_STEP $CREDAL_S_AWAL $CREDAL_S_AKHIR $CREDAL_S_STEP $THRESHOLD_AWAL $THRESHOLD_AKHIR $THRESHOLD_STEP ~/$PATH_MODEL $ID_DT_TRAIN $JNS_DT_TRAIN $PARTITION_TRAIN $ID_DT_TEST $JNS_DT_TEST $PARTITION_TEST
wait

END="$(date +"%r")"
echo "START : $START END : $END"


