
labeling : main.cc Tread_file.cc Tolah_label.cc Tconf_metrix.cc Tbase_dataframe.cc Tdataframe_label.cc  global_func.cc Tip_port_holder.cc Tread_file_darpa.cc Tdataframe_darpa.cc Tfield_filter_darpa.cc Tdatetime_holder.cc
	       g++ -o labeling main.cc Tread_file.cc Tolah_label.cc Tconf_metrix.cc Tbase_dataframe.cc Tdataframe_label.cc  global_func.cc Tip_port_holder.cc Tread_file_darpa.cc Tdataframe_darpa.cc Tfield_filter_darpa.cc Tdatetime_holder.cc -g -I.
