
my_dtsvm : main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc Tbelow_above.cc
	       g++ -o my_dtsvm main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc Tbelow_above.cc -pthread -g -I.
