
my_dtsvm : main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Tconf_metrix.cc
	       g++ -o my_dtsvm main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Tconf_metrix.cc -g -I.
