
my_dtsvm : main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Twrite_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc Tbelow_above.cc Tbase_dataframe.cc
	       g++ -o my_dtsvm -std=c++17 main.cc svm.cpp Tdec_tree.cc Tmy_svm.cc Tdataframe.cc Tread_file.cc Twrite_file.cc Tconf_metrix.cc Tmy_dttype.cc Tlabel_stat.cc Tbelow_above.cc Tbase_dataframe.cc -lstdc++fs -pthread -g -I.
